/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BooleanFilter } from "../../util/BooleanFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { ExceptionalClosureListRelationFilter } from "../../exceptionalClosure/base/ExceptionalClosureListRelationFilter";
import { IntFilter } from "../../util/IntFilter";
import { StringFilter } from "../../util/StringFilter";
import { ScheduleListRelationFilter } from "../../schedule/base/ScheduleListRelationFilter";
import { WeeklyProfessorAvailabilityListRelationFilter } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailabilityListRelationFilter";
import { WeeklyTeachingLoadListRelationFilter } from "../../weeklyTeachingLoad/base/WeeklyTeachingLoadListRelationFilter";

@InputType()
class AcademicWeekWhereInput {
  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  active?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  endDate?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => ExceptionalClosureListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExceptionalClosureListRelationFilter)
  @IsOptional()
  @Field(() => ExceptionalClosureListRelationFilter, {
    nullable: true,
  })
  exceptionalClosures?: ExceptionalClosureListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: BooleanFilter,
  })
  @Type(() => BooleanFilter)
  @IsOptional()
  @Field(() => BooleanFilter, {
    nullable: true,
  })
  locked?: BooleanFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  name?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => ScheduleListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScheduleListRelationFilter)
  @IsOptional()
  @Field(() => ScheduleListRelationFilter, {
    nullable: true,
  })
  schedule?: ScheduleListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  startDate?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => WeeklyProfessorAvailabilityListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WeeklyProfessorAvailabilityListRelationFilter)
  @IsOptional()
  @Field(() => WeeklyProfessorAvailabilityListRelationFilter, {
    nullable: true,
  })
  weeklyProfessorAvailability?: WeeklyProfessorAvailabilityListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => WeeklyTeachingLoadListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WeeklyTeachingLoadListRelationFilter)
  @IsOptional()
  @Field(() => WeeklyTeachingLoadListRelationFilter, {
    nullable: true,
  })
  weeklyTeachingLoads?: WeeklyTeachingLoadListRelationFilter;
}

export { AcademicWeekWhereInput as AcademicWeekWhereInput };
