/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsDate,
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ExceptionalClosureCreateNestedManyWithoutAcademicWeeksInput } from "./ExceptionalClosureCreateNestedManyWithoutAcademicWeeksInput";
import { ScheduleCreateNestedManyWithoutAcademicWeeksInput } from "./ScheduleCreateNestedManyWithoutAcademicWeeksInput";
import { WeeklyProfessorAvailabilityCreateNestedManyWithoutAcademicWeeksInput } from "./WeeklyProfessorAvailabilityCreateNestedManyWithoutAcademicWeeksInput";
import { WeeklyTeachingLoadCreateNestedManyWithoutAcademicWeeksInput } from "./WeeklyTeachingLoadCreateNestedManyWithoutAcademicWeeksInput";

@InputType()
class AcademicWeekCreateInput {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  active!: boolean;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  endDate!: Date;

  @ApiProperty({
    required: false,
    type: () => ExceptionalClosureCreateNestedManyWithoutAcademicWeeksInput,
  })
  @ValidateNested()
  @Type(() => ExceptionalClosureCreateNestedManyWithoutAcademicWeeksInput)
  @IsOptional()
  @Field(() => ExceptionalClosureCreateNestedManyWithoutAcademicWeeksInput, {
    nullable: true,
  })
  exceptionalClosures?: ExceptionalClosureCreateNestedManyWithoutAcademicWeeksInput;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  locked!: boolean;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ScheduleCreateNestedManyWithoutAcademicWeeksInput,
  })
  @ValidateNested()
  @Type(() => ScheduleCreateNestedManyWithoutAcademicWeeksInput)
  @IsOptional()
  @Field(() => ScheduleCreateNestedManyWithoutAcademicWeeksInput, {
    nullable: true,
  })
  schedule?: ScheduleCreateNestedManyWithoutAcademicWeeksInput;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  startDate!: Date;

  @ApiProperty({
    required: false,
    type: () =>
      WeeklyProfessorAvailabilityCreateNestedManyWithoutAcademicWeeksInput,
  })
  @ValidateNested()
  @Type(
    () => WeeklyProfessorAvailabilityCreateNestedManyWithoutAcademicWeeksInput
  )
  @IsOptional()
  @Field(
    () => WeeklyProfessorAvailabilityCreateNestedManyWithoutAcademicWeeksInput,
    {
      nullable: true,
    }
  )
  weeklyProfessorAvailability?: WeeklyProfessorAvailabilityCreateNestedManyWithoutAcademicWeeksInput;

  @ApiProperty({
    required: false,
    type: () => WeeklyTeachingLoadCreateNestedManyWithoutAcademicWeeksInput,
  })
  @ValidateNested()
  @Type(() => WeeklyTeachingLoadCreateNestedManyWithoutAcademicWeeksInput)
  @IsOptional()
  @Field(() => WeeklyTeachingLoadCreateNestedManyWithoutAcademicWeeksInput, {
    nullable: true,
  })
  weeklyTeachingLoads?: WeeklyTeachingLoadCreateNestedManyWithoutAcademicWeeksInput;
}

export { AcademicWeekCreateInput as AcademicWeekCreateInput };
