/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  IsDate,
  ValidateNested,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ExceptionalClosureUpdateManyWithoutAcademicWeeksInput } from "./ExceptionalClosureUpdateManyWithoutAcademicWeeksInput";
import { ScheduleUpdateManyWithoutAcademicWeeksInput } from "./ScheduleUpdateManyWithoutAcademicWeeksInput";
import { WeeklyProfessorAvailabilityUpdateManyWithoutAcademicWeeksInput } from "./WeeklyProfessorAvailabilityUpdateManyWithoutAcademicWeeksInput";
import { WeeklyTeachingLoadUpdateManyWithoutAcademicWeeksInput } from "./WeeklyTeachingLoadUpdateManyWithoutAcademicWeeksInput";

@InputType()
class AcademicWeekUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  active?: boolean;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endDate?: Date;

  @ApiProperty({
    required: false,
    type: () => ExceptionalClosureUpdateManyWithoutAcademicWeeksInput,
  })
  @ValidateNested()
  @Type(() => ExceptionalClosureUpdateManyWithoutAcademicWeeksInput)
  @IsOptional()
  @Field(() => ExceptionalClosureUpdateManyWithoutAcademicWeeksInput, {
    nullable: true,
  })
  exceptionalClosures?: ExceptionalClosureUpdateManyWithoutAcademicWeeksInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  locked?: boolean;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ScheduleUpdateManyWithoutAcademicWeeksInput,
  })
  @ValidateNested()
  @Type(() => ScheduleUpdateManyWithoutAcademicWeeksInput)
  @IsOptional()
  @Field(() => ScheduleUpdateManyWithoutAcademicWeeksInput, {
    nullable: true,
  })
  schedule?: ScheduleUpdateManyWithoutAcademicWeeksInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date;

  @ApiProperty({
    required: false,
    type: () => WeeklyProfessorAvailabilityUpdateManyWithoutAcademicWeeksInput,
  })
  @ValidateNested()
  @Type(() => WeeklyProfessorAvailabilityUpdateManyWithoutAcademicWeeksInput)
  @IsOptional()
  @Field(() => WeeklyProfessorAvailabilityUpdateManyWithoutAcademicWeeksInput, {
    nullable: true,
  })
  weeklyProfessorAvailability?: WeeklyProfessorAvailabilityUpdateManyWithoutAcademicWeeksInput;

  @ApiProperty({
    required: false,
    type: () => WeeklyTeachingLoadUpdateManyWithoutAcademicWeeksInput,
  })
  @ValidateNested()
  @Type(() => WeeklyTeachingLoadUpdateManyWithoutAcademicWeeksInput)
  @IsOptional()
  @Field(() => WeeklyTeachingLoadUpdateManyWithoutAcademicWeeksInput, {
    nullable: true,
  })
  weeklyTeachingLoads?: WeeklyTeachingLoadUpdateManyWithoutAcademicWeeksInput;
}

export { AcademicWeekUpdateInput as AcademicWeekUpdateInput };
