/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AcademicWeekService } from "../academicWeek.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AcademicWeekCreateInput } from "./AcademicWeekCreateInput";
import { AcademicWeek } from "./AcademicWeek";
import { AcademicWeekFindManyArgs } from "./AcademicWeekFindManyArgs";
import { AcademicWeekWhereUniqueInput } from "./AcademicWeekWhereUniqueInput";
import { AcademicWeekUpdateInput } from "./AcademicWeekUpdateInput";
import { ExceptionalClosureFindManyArgs } from "../../exceptionalClosure/base/ExceptionalClosureFindManyArgs";
import { ExceptionalClosure } from "../../exceptionalClosure/base/ExceptionalClosure";
import { ExceptionalClosureWhereUniqueInput } from "../../exceptionalClosure/base/ExceptionalClosureWhereUniqueInput";
import { ScheduleFindManyArgs } from "../../schedule/base/ScheduleFindManyArgs";
import { Schedule } from "../../schedule/base/Schedule";
import { ScheduleWhereUniqueInput } from "../../schedule/base/ScheduleWhereUniqueInput";
import { WeeklyProfessorAvailabilityFindManyArgs } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailabilityFindManyArgs";
import { WeeklyProfessorAvailability } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailability";
import { WeeklyProfessorAvailabilityWhereUniqueInput } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailabilityWhereUniqueInput";
import { WeeklyTeachingLoadFindManyArgs } from "../../weeklyTeachingLoad/base/WeeklyTeachingLoadFindManyArgs";
import { WeeklyTeachingLoad } from "../../weeklyTeachingLoad/base/WeeklyTeachingLoad";
import { WeeklyTeachingLoadWhereUniqueInput } from "../../weeklyTeachingLoad/base/WeeklyTeachingLoadWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AcademicWeekControllerBase {
  constructor(
    protected readonly service: AcademicWeekService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AcademicWeek })
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAcademicWeek(
    @common.Body() data: AcademicWeekCreateInput
  ): Promise<AcademicWeek> {
    return await this.service.createAcademicWeek({
      data: data,
      select: {
        active: true,
        endDate: true,
        id: true,
        locked: true,
        name: true,
        startDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AcademicWeek] })
  @ApiNestedQuery(AcademicWeekFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async academicWeeks(@common.Req() request: Request): Promise<AcademicWeek[]> {
    const args = plainToClass(AcademicWeekFindManyArgs, request.query);
    return this.service.academicWeeks({
      ...args,
      select: {
        active: true,
        endDate: true,
        id: true,
        locked: true,
        name: true,
        startDate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AcademicWeek })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async academicWeek(
    @common.Param() params: AcademicWeekWhereUniqueInput
  ): Promise<AcademicWeek | null> {
    const result = await this.service.academicWeek({
      where: params,
      select: {
        active: true,
        endDate: true,
        id: true,
        locked: true,
        name: true,
        startDate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AcademicWeek })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAcademicWeek(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() data: AcademicWeekUpdateInput
  ): Promise<AcademicWeek | null> {
    try {
      return await this.service.updateAcademicWeek({
        where: params,
        data: data,
        select: {
          active: true,
          endDate: true,
          id: true,
          locked: true,
          name: true,
          startDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AcademicWeek })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAcademicWeek(
    @common.Param() params: AcademicWeekWhereUniqueInput
  ): Promise<AcademicWeek | null> {
    try {
      return await this.service.deleteAcademicWeek({
        where: params,
        select: {
          active: true,
          endDate: true,
          id: true,
          locked: true,
          name: true,
          startDate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/exceptionalClosures")
  @ApiNestedQuery(ExceptionalClosureFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExceptionalClosure",
    action: "read",
    possession: "any",
  })
  async findExceptionalClosures(
    @common.Req() request: Request,
    @common.Param() params: AcademicWeekWhereUniqueInput
  ): Promise<ExceptionalClosure[]> {
    const query = plainToClass(ExceptionalClosureFindManyArgs, request.query);
    const results = await this.service.findExceptionalClosures(params.id, {
      ...query,
      select: {
        id: true,
        reason: true,

        timeSlot: {
          select: {
            id: true,
          },
        },

        week: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/exceptionalClosures")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async connectExceptionalClosures(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: ExceptionalClosureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exceptionalClosures: {
        connect: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/exceptionalClosures")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async updateExceptionalClosures(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: ExceptionalClosureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exceptionalClosures: {
        set: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/exceptionalClosures")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async disconnectExceptionalClosures(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: ExceptionalClosureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      exceptionalClosures: {
        disconnect: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/schedule")
  @ApiNestedQuery(ScheduleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Schedule",
    action: "read",
    possession: "any",
  })
  async findSchedule(
    @common.Req() request: Request,
    @common.Param() params: AcademicWeekWhereUniqueInput
  ): Promise<Schedule[]> {
    const query = plainToClass(ScheduleFindManyArgs, request.query);
    const results = await this.service.findSchedule(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        professor: {
          select: {
            id: true,
          },
        },

        room: {
          select: {
            id: true,
          },
        },

        teachingType: true,

        timeSlot: {
          select: {
            id: true,
          },
        },

        week: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/schedule")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async connectSchedule(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: ScheduleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schedule: {
        connect: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/schedule")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async updateSchedule(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: ScheduleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schedule: {
        set: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/schedule")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async disconnectSchedule(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: ScheduleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      schedule: {
        disconnect: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/weeklyProfessorAvailability")
  @ApiNestedQuery(WeeklyProfessorAvailabilityFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WeeklyProfessorAvailability",
    action: "read",
    possession: "any",
  })
  async findWeeklyProfessorAvailability(
    @common.Req() request: Request,
    @common.Param() params: AcademicWeekWhereUniqueInput
  ): Promise<WeeklyProfessorAvailability[]> {
    const query = plainToClass(
      WeeklyProfessorAvailabilityFindManyArgs,
      request.query
    );
    const results = await this.service.findWeeklyProfessorAvailability(
      params.id,
      {
        ...query,
        select: {
          id: true,
          isAvailable: true,

          professor: {
            select: {
              id: true,
            },
          },

          timeSlot: {
            select: {
              id: true,
            },
          },

          week: {
            select: {
              id: true,
            },
          },
        },
      }
    );
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/weeklyProfessorAvailability")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async connectWeeklyProfessorAvailability(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: WeeklyProfessorAvailabilityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      weeklyProfessorAvailability: {
        connect: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/weeklyProfessorAvailability")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async updateWeeklyProfessorAvailability(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: WeeklyProfessorAvailabilityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      weeklyProfessorAvailability: {
        set: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/weeklyProfessorAvailability")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async disconnectWeeklyProfessorAvailability(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: WeeklyProfessorAvailabilityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      weeklyProfessorAvailability: {
        disconnect: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/weeklyTeachingLoads")
  @ApiNestedQuery(WeeklyTeachingLoadFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WeeklyTeachingLoad",
    action: "read",
    possession: "any",
  })
  async findWeeklyTeachingLoads(
    @common.Req() request: Request,
    @common.Param() params: AcademicWeekWhereUniqueInput
  ): Promise<WeeklyTeachingLoad[]> {
    const query = plainToClass(WeeklyTeachingLoadFindManyArgs, request.query);
    const results = await this.service.findWeeklyTeachingLoads(params.id, {
      ...query,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        group: {
          select: {
            id: true,
          },
        },

        hoursRequired: true,
        id: true,
        teachingType: true,

        week: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/weeklyTeachingLoads")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async connectWeeklyTeachingLoads(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: WeeklyTeachingLoadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      weeklyTeachingLoads: {
        connect: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/weeklyTeachingLoads")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async updateWeeklyTeachingLoads(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: WeeklyTeachingLoadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      weeklyTeachingLoads: {
        set: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/weeklyTeachingLoads")
  @nestAccessControl.UseRoles({
    resource: "AcademicWeek",
    action: "update",
    possession: "any",
  })
  async disconnectWeeklyTeachingLoads(
    @common.Param() params: AcademicWeekWhereUniqueInput,
    @common.Body() body: WeeklyTeachingLoadWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      weeklyTeachingLoads: {
        disconnect: body,
      },
    };
    await this.service.updateAcademicWeek({
      where: params,
      data,
      select: { id: true },
    });
  }
}
