/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsDate,
  ValidateNested,
  IsOptional,
  IsInt,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { ExceptionalClosure } from "../../exceptionalClosure/base/ExceptionalClosure";
import { Schedule } from "../../schedule/base/Schedule";
import { WeeklyProfessorAvailability } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailability";
import { WeeklyTeachingLoad } from "../../weeklyTeachingLoad/base/WeeklyTeachingLoad";

@ObjectType()
class AcademicWeek {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  active!: boolean;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  endDate!: Date;

  @ApiProperty({
    required: false,
    type: () => [ExceptionalClosure],
  })
  @ValidateNested()
  @Type(() => ExceptionalClosure)
  @IsOptional()
  exceptionalClosures?: Array<ExceptionalClosure>;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  locked!: boolean;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => [Schedule],
  })
  @ValidateNested()
  @Type(() => Schedule)
  @IsOptional()
  schedule?: Array<Schedule>;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  startDate!: Date;

  @ApiProperty({
    required: false,
    type: () => [WeeklyProfessorAvailability],
  })
  @ValidateNested()
  @Type(() => WeeklyProfessorAvailability)
  @IsOptional()
  weeklyProfessorAvailability?: Array<WeeklyProfessorAvailability>;

  @ApiProperty({
    required: false,
    type: () => [WeeklyTeachingLoad],
  })
  @ValidateNested()
  @Type(() => WeeklyTeachingLoad)
  @IsOptional()
  weeklyTeachingLoads?: Array<WeeklyTeachingLoad>;
}

export { AcademicWeek as AcademicWeek };
