/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { GroupWhereUniqueInput } from "../../group/base/GroupWhereUniqueInput";
import { ProfessorWhereUniqueInput } from "../../professor/base/ProfessorWhereUniqueInput";
import { RoomWhereUniqueInput } from "../../room/base/RoomWhereUniqueInput";
import { TimeSlotWhereUniqueInput } from "../../timeSlot/base/TimeSlotWhereUniqueInput";
import { AcademicWeekWhereUniqueInput } from "../../academicWeek/base/AcademicWeekWhereUniqueInput";

@InputType()
class ScheduleUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CourseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseWhereUniqueInput)
  @IsOptional()
  @Field(() => CourseWhereUniqueInput, {
    nullable: true,
  })
  course?: CourseWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => GroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GroupWhereUniqueInput)
  @IsOptional()
  @Field(() => GroupWhereUniqueInput, {
    nullable: true,
  })
  group?: GroupWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ProfessorWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProfessorWhereUniqueInput)
  @IsOptional()
  @Field(() => ProfessorWhereUniqueInput, {
    nullable: true,
  })
  professor?: ProfessorWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => RoomWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RoomWhereUniqueInput)
  @IsOptional()
  @Field(() => RoomWhereUniqueInput, {
    nullable: true,
  })
  room?: RoomWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  teachingType?: string;

  @ApiProperty({
    required: false,
    type: () => TimeSlotWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TimeSlotWhereUniqueInput)
  @IsOptional()
  @Field(() => TimeSlotWhereUniqueInput, {
    nullable: true,
  })
  timeSlot?: TimeSlotWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AcademicWeekWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AcademicWeekWhereUniqueInput)
  @IsOptional()
  @Field(() => AcademicWeekWhereUniqueInput, {
    nullable: true,
  })
  week?: AcademicWeekWhereUniqueInput;
}

export { ScheduleUpdateInput as ScheduleUpdateInput };
