/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CourseWhereUniqueInput } from "../../course/base/CourseWhereUniqueInput";
import { ValidateNested, IsString, MaxLength } from "class-validator";
import { Type } from "class-transformer";
import { GroupWhereUniqueInput } from "../../group/base/GroupWhereUniqueInput";
import { ProfessorWhereUniqueInput } from "../../professor/base/ProfessorWhereUniqueInput";
import { RoomWhereUniqueInput } from "../../room/base/RoomWhereUniqueInput";
import { TimeSlotWhereUniqueInput } from "../../timeSlot/base/TimeSlotWhereUniqueInput";
import { AcademicWeekWhereUniqueInput } from "../../academicWeek/base/AcademicWeekWhereUniqueInput";

@InputType()
class ScheduleCreateInput {
  @ApiProperty({
    required: true,
    type: () => CourseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CourseWhereUniqueInput)
  @Field(() => CourseWhereUniqueInput)
  course!: CourseWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => GroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GroupWhereUniqueInput)
  @Field(() => GroupWhereUniqueInput)
  group!: GroupWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => ProfessorWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProfessorWhereUniqueInput)
  @Field(() => ProfessorWhereUniqueInput)
  professor!: ProfessorWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => RoomWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RoomWhereUniqueInput)
  @Field(() => RoomWhereUniqueInput)
  room!: RoomWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  teachingType!: string;

  @ApiProperty({
    required: true,
    type: () => TimeSlotWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TimeSlotWhereUniqueInput)
  @Field(() => TimeSlotWhereUniqueInput)
  timeSlot!: TimeSlotWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => AcademicWeekWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AcademicWeekWhereUniqueInput)
  @Field(() => AcademicWeekWhereUniqueInput)
  week!: AcademicWeekWhereUniqueInput;
}

export { ScheduleCreateInput as ScheduleCreateInput };
