/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  ValidateNested,
} from "class-validator";
import { ProfessorAssignment } from "../../professorAssignment/base/ProfessorAssignment";
import { Type } from "class-transformer";
import { Schedule } from "../../schedule/base/Schedule";
import { WeeklyProfessorAvailability } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailability";

@ObjectType()
class Professor {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  department!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => [ProfessorAssignment],
  })
  @ValidateNested()
  @Type(() => ProfessorAssignment)
  @IsOptional()
  professorAssignments?: Array<ProfessorAssignment>;

  @ApiProperty({
    required: false,
    type: () => [Schedule],
  })
  @ValidateNested()
  @Type(() => Schedule)
  @IsOptional()
  schedule?: Array<Schedule>;

  @ApiProperty({
    required: false,
    type: () => [WeeklyProfessorAvailability],
  })
  @ValidateNested()
  @Type(() => WeeklyProfessorAvailability)
  @IsOptional()
  weeklyProfessorAvailability?: Array<WeeklyProfessorAvailability>;
}

export { Professor as Professor };
