/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Max,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { ExceptionalClosureUpdateManyWithoutTimeSlotsInput } from "./ExceptionalClosureUpdateManyWithoutTimeSlotsInput";
import { ScheduleUpdateManyWithoutTimeSlotsInput } from "./ScheduleUpdateManyWithoutTimeSlotsInput";
import { WeeklyProfessorAvailabilityUpdateManyWithoutTimeSlotsInput } from "./WeeklyProfessorAvailabilityUpdateManyWithoutTimeSlotsInput";

@InputType()
class TimeSlotUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  dayOfWeek?: number;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  endTime?: Date;

  @ApiProperty({
    required: false,
    type: () => ExceptionalClosureUpdateManyWithoutTimeSlotsInput,
  })
  @ValidateNested()
  @Type(() => ExceptionalClosureUpdateManyWithoutTimeSlotsInput)
  @IsOptional()
  @Field(() => ExceptionalClosureUpdateManyWithoutTimeSlotsInput, {
    nullable: true,
  })
  exceptionalClosures?: ExceptionalClosureUpdateManyWithoutTimeSlotsInput;

  @ApiProperty({
    required: false,
    type: () => ScheduleUpdateManyWithoutTimeSlotsInput,
  })
  @ValidateNested()
  @Type(() => ScheduleUpdateManyWithoutTimeSlotsInput)
  @IsOptional()
  @Field(() => ScheduleUpdateManyWithoutTimeSlotsInput, {
    nullable: true,
  })
  schedule?: ScheduleUpdateManyWithoutTimeSlotsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  slotIndex?: number;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startTime?: Date;

  @ApiProperty({
    required: false,
    type: () => WeeklyProfessorAvailabilityUpdateManyWithoutTimeSlotsInput,
  })
  @ValidateNested()
  @Type(() => WeeklyProfessorAvailabilityUpdateManyWithoutTimeSlotsInput)
  @IsOptional()
  @Field(() => WeeklyProfessorAvailabilityUpdateManyWithoutTimeSlotsInput, {
    nullable: true,
  })
  weeklyProfessorAvailability?: WeeklyProfessorAvailabilityUpdateManyWithoutTimeSlotsInput;
}

export { TimeSlotUpdateInput as TimeSlotUpdateInput };
