/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Max,
  IsDate,
  ValidateNested,
  IsOptional,
} from "class-validator";
import { Type } from "class-transformer";
import { ExceptionalClosure } from "../../exceptionalClosure/base/ExceptionalClosure";
import { Schedule } from "../../schedule/base/Schedule";
import { WeeklyProfessorAvailability } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailability";

@ObjectType()
class TimeSlot {
  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  dayOfWeek!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  endTime!: Date;

  @ApiProperty({
    required: false,
    type: () => [ExceptionalClosure],
  })
  @ValidateNested()
  @Type(() => ExceptionalClosure)
  @IsOptional()
  exceptionalClosures?: Array<ExceptionalClosure>;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: () => [Schedule],
  })
  @ValidateNested()
  @Type(() => Schedule)
  @IsOptional()
  schedule?: Array<Schedule>;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  slotIndex!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  startTime!: Date;

  @ApiProperty({
    required: false,
    type: () => [WeeklyProfessorAvailability],
  })
  @ValidateNested()
  @Type(() => WeeklyProfessorAvailability)
  @IsOptional()
  weeklyProfessorAvailability?: Array<WeeklyProfessorAvailability>;
}

export { TimeSlot as TimeSlot };
