/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IntFilter } from "../../util/IntFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { DateTimeFilter } from "../../util/DateTimeFilter";
import { ExceptionalClosureListRelationFilter } from "../../exceptionalClosure/base/ExceptionalClosureListRelationFilter";
import { ScheduleListRelationFilter } from "../../schedule/base/ScheduleListRelationFilter";
import { WeeklyProfessorAvailabilityListRelationFilter } from "../../weeklyProfessorAvailability/base/WeeklyProfessorAvailabilityListRelationFilter";

@InputType()
class TimeSlotWhereInput {
  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  dayOfWeek?: IntFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  endTime?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => ExceptionalClosureListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExceptionalClosureListRelationFilter)
  @IsOptional()
  @Field(() => ExceptionalClosureListRelationFilter, {
    nullable: true,
  })
  exceptionalClosures?: ExceptionalClosureListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  id?: IntFilter;

  @ApiProperty({
    required: false,
    type: () => ScheduleListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ScheduleListRelationFilter)
  @IsOptional()
  @Field(() => ScheduleListRelationFilter, {
    nullable: true,
  })
  schedule?: ScheduleListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntFilter,
  })
  @Type(() => IntFilter)
  @IsOptional()
  @Field(() => IntFilter, {
    nullable: true,
  })
  slotIndex?: IntFilter;

  @ApiProperty({
    required: false,
    type: DateTimeFilter,
  })
  @Type(() => DateTimeFilter)
  @IsOptional()
  @Field(() => DateTimeFilter, {
    nullable: true,
  })
  startTime?: DateTimeFilter;

  @ApiProperty({
    required: false,
    type: () => WeeklyProfessorAvailabilityListRelationFilter,
  })
  @ValidateNested()
  @Type(() => WeeklyProfessorAvailabilityListRelationFilter)
  @IsOptional()
  @Field(() => WeeklyProfessorAvailabilityListRelationFilter, {
    nullable: true,
  })
  weeklyProfessorAvailability?: WeeklyProfessorAvailabilityListRelationFilter;
}

export { TimeSlotWhereInput as TimeSlotWhereInput };
