/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { GroupOverlapUpdateManyWithoutGroupsInput } from "./GroupOverlapUpdateManyWithoutGroupsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsInt,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { ProfessorAssignmentUpdateManyWithoutGroupsInput } from "./ProfessorAssignmentUpdateManyWithoutGroupsInput";
import { ScheduleUpdateManyWithoutGroupsInput } from "./ScheduleUpdateManyWithoutGroupsInput";
import { WeeklyTeachingLoadUpdateManyWithoutGroupsInput } from "./WeeklyTeachingLoadUpdateManyWithoutGroupsInput";

@InputType()
class GroupUpdateInput {
  @ApiProperty({
    required: false,
    type: () => GroupOverlapUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupOverlapUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupOverlapUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  groupOverlaps1?: GroupOverlapUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: () => GroupOverlapUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => GroupOverlapUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => GroupOverlapUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  groupOverlaps2?: GroupOverlapUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ProfessorAssignmentUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => ProfessorAssignmentUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => ProfessorAssignmentUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  professorAssignments?: ProfessorAssignmentUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: () => ScheduleUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => ScheduleUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => ScheduleUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  schedule?: ScheduleUpdateManyWithoutGroupsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  semester?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specialization?: string;

  @ApiProperty({
    required: false,
    type: () => WeeklyTeachingLoadUpdateManyWithoutGroupsInput,
  })
  @ValidateNested()
  @Type(() => WeeklyTeachingLoadUpdateManyWithoutGroupsInput)
  @IsOptional()
  @Field(() => WeeklyTeachingLoadUpdateManyWithoutGroupsInput, {
    nullable: true,
  })
  weeklyTeachingLoads?: WeeklyTeachingLoadUpdateManyWithoutGroupsInput;
}

export { GroupUpdateInput as GroupUpdateInput };
