/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExceptionalClosureService } from "../exceptionalClosure.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExceptionalClosureCreateInput } from "./ExceptionalClosureCreateInput";
import { ExceptionalClosure } from "./ExceptionalClosure";
import { ExceptionalClosureFindManyArgs } from "./ExceptionalClosureFindManyArgs";
import { ExceptionalClosureWhereUniqueInput } from "./ExceptionalClosureWhereUniqueInput";
import { ExceptionalClosureUpdateInput } from "./ExceptionalClosureUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExceptionalClosureControllerBase {
  constructor(
    protected readonly service: ExceptionalClosureService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExceptionalClosure })
  @nestAccessControl.UseRoles({
    resource: "ExceptionalClosure",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExceptionalClosure(
    @common.Body() data: ExceptionalClosureCreateInput
  ): Promise<ExceptionalClosure> {
    return await this.service.createExceptionalClosure({
      data: {
        ...data,

        timeSlot: {
          connect: data.timeSlot,
        },

        week: {
          connect: data.week,
        },
      },
      select: {
        id: true,
        reason: true,

        timeSlot: {
          select: {
            id: true,
          },
        },

        week: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExceptionalClosure] })
  @ApiNestedQuery(ExceptionalClosureFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExceptionalClosure",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async exceptionalClosures(
    @common.Req() request: Request
  ): Promise<ExceptionalClosure[]> {
    const args = plainToClass(ExceptionalClosureFindManyArgs, request.query);
    return this.service.exceptionalClosures({
      ...args,
      select: {
        id: true,
        reason: true,

        timeSlot: {
          select: {
            id: true,
          },
        },

        week: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExceptionalClosure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExceptionalClosure",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async exceptionalClosure(
    @common.Param() params: ExceptionalClosureWhereUniqueInput
  ): Promise<ExceptionalClosure | null> {
    const result = await this.service.exceptionalClosure({
      where: params,
      select: {
        id: true,
        reason: true,

        timeSlot: {
          select: {
            id: true,
          },
        },

        week: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExceptionalClosure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExceptionalClosure",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExceptionalClosure(
    @common.Param() params: ExceptionalClosureWhereUniqueInput,
    @common.Body() data: ExceptionalClosureUpdateInput
  ): Promise<ExceptionalClosure | null> {
    try {
      return await this.service.updateExceptionalClosure({
        where: params,
        data: {
          ...data,

          timeSlot: {
            connect: data.timeSlot,
          },

          week: {
            connect: data.week,
          },
        },
        select: {
          id: true,
          reason: true,

          timeSlot: {
            select: {
              id: true,
            },
          },

          week: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExceptionalClosure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExceptionalClosure",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExceptionalClosure(
    @common.Param() params: ExceptionalClosureWhereUniqueInput
  ): Promise<ExceptionalClosure | null> {
    try {
      return await this.service.deleteExceptionalClosure({
        where: params,
        select: {
          id: true,
          reason: true,

          timeSlot: {
            select: {
              id: true,
            },
          },

          week: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
