/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ProfessorAssignmentService } from "../professorAssignment.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ProfessorAssignmentCreateInput } from "./ProfessorAssignmentCreateInput";
import { ProfessorAssignment } from "./ProfessorAssignment";
import { ProfessorAssignmentFindManyArgs } from "./ProfessorAssignmentFindManyArgs";
import { ProfessorAssignmentWhereUniqueInput } from "./ProfessorAssignmentWhereUniqueInput";
import { ProfessorAssignmentUpdateInput } from "./ProfessorAssignmentUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ProfessorAssignmentControllerBase {
  constructor(
    protected readonly service: ProfessorAssignmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ProfessorAssignment })
  @nestAccessControl.UseRoles({
    resource: "ProfessorAssignment",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createProfessorAssignment(
    @common.Body() data: ProfessorAssignmentCreateInput
  ): Promise<ProfessorAssignment> {
    return await this.service.createProfessorAssignment({
      data: {
        ...data,

        course: {
          connect: data.course,
        },

        group: {
          connect: data.group,
        },

        professor: {
          connect: data.professor,
        },
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        professor: {
          select: {
            id: true,
          },
        },

        teachingType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ProfessorAssignment] })
  @ApiNestedQuery(ProfessorAssignmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ProfessorAssignment",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async professorAssignments(
    @common.Req() request: Request
  ): Promise<ProfessorAssignment[]> {
    const args = plainToClass(ProfessorAssignmentFindManyArgs, request.query);
    return this.service.professorAssignments({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        professor: {
          select: {
            id: true,
          },
        },

        teachingType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ProfessorAssignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfessorAssignment",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async professorAssignment(
    @common.Param() params: ProfessorAssignmentWhereUniqueInput
  ): Promise<ProfessorAssignment | null> {
    const result = await this.service.professorAssignment({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        professor: {
          select: {
            id: true,
          },
        },

        teachingType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ProfessorAssignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfessorAssignment",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateProfessorAssignment(
    @common.Param() params: ProfessorAssignmentWhereUniqueInput,
    @common.Body() data: ProfessorAssignmentUpdateInput
  ): Promise<ProfessorAssignment | null> {
    try {
      return await this.service.updateProfessorAssignment({
        where: params,
        data: {
          ...data,

          course: {
            connect: data.course,
          },

          group: {
            connect: data.group,
          },

          professor: {
            connect: data.professor,
          },
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          group: {
            select: {
              id: true,
            },
          },

          id: true,

          professor: {
            select: {
              id: true,
            },
          },

          teachingType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ProfessorAssignment })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ProfessorAssignment",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteProfessorAssignment(
    @common.Param() params: ProfessorAssignmentWhereUniqueInput
  ): Promise<ProfessorAssignment | null> {
    try {
      return await this.service.deleteProfessorAssignment({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          group: {
            select: {
              id: true,
            },
          },

          id: true,

          professor: {
            select: {
              id: true,
            },
          },

          teachingType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
