/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  ValidateNested,
  IsOptional,
  IsInt,
  Max,
} from "class-validator";
import { ProfessorAssignmentCreateNestedManyWithoutCoursesInput } from "./ProfessorAssignmentCreateNestedManyWithoutCoursesInput";
import { Type } from "class-transformer";
import { ScheduleCreateNestedManyWithoutCoursesInput } from "./ScheduleCreateNestedManyWithoutCoursesInput";
import { WeeklyTeachingLoadCreateNestedManyWithoutCoursesInput } from "./WeeklyTeachingLoadCreateNestedManyWithoutCoursesInput";

@InputType()
class CourseCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  code!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => ProfessorAssignmentCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ProfessorAssignmentCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ProfessorAssignmentCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  professorAssignments?: ProfessorAssignmentCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => ScheduleCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ScheduleCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ScheduleCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  schedule?: ScheduleCreateNestedManyWithoutCoursesInput;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @Field(() => Number)
  semester!: number;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  specialization!: string;

  @ApiProperty({
    required: false,
    type: () => WeeklyTeachingLoadCreateNestedManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => WeeklyTeachingLoadCreateNestedManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => WeeklyTeachingLoadCreateNestedManyWithoutCoursesInput, {
    nullable: true,
  })
  weeklyTeachingLoads?: WeeklyTeachingLoadCreateNestedManyWithoutCoursesInput;
}

export { CourseCreateInput as CourseCreateInput };
