/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsInt,
  Max,
} from "class-validator";
import { ProfessorAssignmentUpdateManyWithoutCoursesInput } from "./ProfessorAssignmentUpdateManyWithoutCoursesInput";
import { Type } from "class-transformer";
import { ScheduleUpdateManyWithoutCoursesInput } from "./ScheduleUpdateManyWithoutCoursesInput";
import { WeeklyTeachingLoadUpdateManyWithoutCoursesInput } from "./WeeklyTeachingLoadUpdateManyWithoutCoursesInput";

@InputType()
class CourseUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
    type: () => ProfessorAssignmentUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ProfessorAssignmentUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ProfessorAssignmentUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  professorAssignments?: ProfessorAssignmentUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: () => ScheduleUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => ScheduleUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => ScheduleUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  schedule?: ScheduleUpdateManyWithoutCoursesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  semester?: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  specialization?: string;

  @ApiProperty({
    required: false,
    type: () => WeeklyTeachingLoadUpdateManyWithoutCoursesInput,
  })
  @ValidateNested()
  @Type(() => WeeklyTeachingLoadUpdateManyWithoutCoursesInput)
  @IsOptional()
  @Field(() => WeeklyTeachingLoadUpdateManyWithoutCoursesInput, {
    nullable: true,
  })
  weeklyTeachingLoads?: WeeklyTeachingLoadUpdateManyWithoutCoursesInput;
}

export { CourseUpdateInput as CourseUpdateInput };
