/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WeeklyTeachingLoadService } from "../weeklyTeachingLoad.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WeeklyTeachingLoadCreateInput } from "./WeeklyTeachingLoadCreateInput";
import { WeeklyTeachingLoad } from "./WeeklyTeachingLoad";
import { WeeklyTeachingLoadFindManyArgs } from "./WeeklyTeachingLoadFindManyArgs";
import { WeeklyTeachingLoadWhereUniqueInput } from "./WeeklyTeachingLoadWhereUniqueInput";
import { WeeklyTeachingLoadUpdateInput } from "./WeeklyTeachingLoadUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WeeklyTeachingLoadControllerBase {
  constructor(
    protected readonly service: WeeklyTeachingLoadService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WeeklyTeachingLoad })
  @nestAccessControl.UseRoles({
    resource: "WeeklyTeachingLoad",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWeeklyTeachingLoad(
    @common.Body() data: WeeklyTeachingLoadCreateInput
  ): Promise<WeeklyTeachingLoad> {
    return await this.service.createWeeklyTeachingLoad({
      data: {
        ...data,

        course: {
          connect: data.course,
        },

        group: {
          connect: data.group,
        },

        week: {
          connect: data.week,
        },
      },
      select: {
        course: {
          select: {
            id: true,
          },
        },

        group: {
          select: {
            id: true,
          },
        },

        hoursRequired: true,
        id: true,
        teachingType: true,

        week: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WeeklyTeachingLoad] })
  @ApiNestedQuery(WeeklyTeachingLoadFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WeeklyTeachingLoad",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async weeklyTeachingLoads(
    @common.Req() request: Request
  ): Promise<WeeklyTeachingLoad[]> {
    const args = plainToClass(WeeklyTeachingLoadFindManyArgs, request.query);
    return this.service.weeklyTeachingLoads({
      ...args,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        group: {
          select: {
            id: true,
          },
        },

        hoursRequired: true,
        id: true,
        teachingType: true,

        week: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WeeklyTeachingLoad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeeklyTeachingLoad",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async weeklyTeachingLoad(
    @common.Param() params: WeeklyTeachingLoadWhereUniqueInput
  ): Promise<WeeklyTeachingLoad | null> {
    const result = await this.service.weeklyTeachingLoad({
      where: params,
      select: {
        course: {
          select: {
            id: true,
          },
        },

        group: {
          select: {
            id: true,
          },
        },

        hoursRequired: true,
        id: true,
        teachingType: true,

        week: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WeeklyTeachingLoad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeeklyTeachingLoad",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWeeklyTeachingLoad(
    @common.Param() params: WeeklyTeachingLoadWhereUniqueInput,
    @common.Body() data: WeeklyTeachingLoadUpdateInput
  ): Promise<WeeklyTeachingLoad | null> {
    try {
      return await this.service.updateWeeklyTeachingLoad({
        where: params,
        data: {
          ...data,

          course: {
            connect: data.course,
          },

          group: {
            connect: data.group,
          },

          week: {
            connect: data.week,
          },
        },
        select: {
          course: {
            select: {
              id: true,
            },
          },

          group: {
            select: {
              id: true,
            },
          },

          hoursRequired: true,
          id: true,
          teachingType: true,

          week: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WeeklyTeachingLoad })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WeeklyTeachingLoad",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWeeklyTeachingLoad(
    @common.Param() params: WeeklyTeachingLoadWhereUniqueInput
  ): Promise<WeeklyTeachingLoad | null> {
    try {
      return await this.service.deleteWeeklyTeachingLoad({
        where: params,
        select: {
          course: {
            select: {
              id: true,
            },
          },

          group: {
            select: {
              id: true,
            },
          },

          hoursRequired: true,
          id: true,
          teachingType: true,

          week: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
